#!/usr/bin/env bash

workspaces() {
~/.config/eww/bar/scripts/workspaces.lua
}

handle() {
  if [[ ${1:0:9} == "workspace" ]]; then
    workspaces
  fi
}

workspaces

socat - "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
