keys:
  - &main age18de5qeh3lenv478ykpqqrs6wj668lc2urpw4ecjkk89nayewwdssktx693

creation_rules:
  - path_regex: secrets/[^/]+\.key$
    pgp: 4D69D9521390361EF9AF096AEAFA19811BC6CB6D
  - path_regex: secrets/[^/]+\.yaml$
    key_groups:
      - age:
        - *main
