# generated by ‘nixos-generate-config’
{ ... }:
{
  flake.aspects =
    { ... }:
    {
      kerosene = {
        nixos =
          {
            config,
            lib,
            modulesPath,
            ...
          }:
          {

            imports = [
              (modulesPath + "/installer/scan/not-detected.nix")
            ];

            boot.initrd.availableKernelModules = [
              "vmd"
              "xhci_pci"
              "ahci"
              "nvme"
              "usbhid"
              "usb_storage"
              "sd_mod"
            ];
            boot.initrd.kernelModules = [ "dm-snapshot" ];
            boot.kernelModules = [ "kvm-intel" ];
            boot.extraModulePackages = [ ];

            swapDevices = [ ];

            powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
            hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
          };
      };
    };
}
