#!/usr/bin/env bash

get_wm() {
    id=$(xprop -root -notype _NET_SUPPORTING_WM_CHECK)
    id=${id##* }
    wm=$(xprop -id "$id" -notype -len 100 -f _NET_WM_NAME 8t)
    wm=${wm/*WM_NAME = }
    wm=${wm/\"}
    wm=${wm/\"*}

    echo "$wm"
}

current_window=$(tmux display-message -p '#I.0')

# Join all panes
tmux list-windows -F '#I.0' | sed "/^$current_window\$/d" | sort -r | xargs -n1 tmux join-pane -h -d -t "$current_window" -s

# Set layout to dwindle if less than 3 panes, otherwise tiled
pane_count=$(tmux list-panes -F '#P' | wc -l)

if (( pane_count < 4)); then
  ~/.tmux.conf.d/tmux-layout-dwindle brvs
  
  vim_id=$(tmux list-panes -F '#P #{pane_current_command}' | awk '$2 ~ /vim/ { print $1 }' | head -n 1) 

  if [ -n "$vim_id" ] && [ "$vim_id" != "0" ]; then
    tmux swap-pane -d -t "$vim_id" -s "0"
  fi

  # Redraw vim pane
  tmux send-keys -t "$vim_id" C-l

else
  tmux select-layout tiled
fi

# If awesomewm is used, change sizes
if [ "$(get_wm)" = "awesome" ]; then
  awm_screen_width=$(echo "return client.focus.screen.geometry.width" | awesome-client | grep -o '[0-9]*')
  awm_window_count=$(echo "return #client.focus.screen.clients" | awesome-client | grep -o '[0-9]*')
  # 2K or bigger screen in question
  if (( awm_screen_width > 2048 )); then
    # If only one window on the screen
    if (( awm_window_count == 1 )); then
      echo "client.focus.screen.padding = 0" | awesome-client # Set padding to 0
    fi
  fi
fi
